# Generated by Django 4.2.19 on 2026-06-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Good_Health_Wellbeing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
    ]
