# Generated by Django 6.0.5 on 2026-06-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Good_Health_Wellbeing', '0003_cuisine_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='anonymoususer', max_length=50),
        ),
    ]
