# Generated by Django 6.0.5 on 2026-06-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Good_Health_Wellbeing', '0005_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Good_Health_Wellbeing.diet'),
        ),
    ]
