# Generated by Django 6.0.5 on 2026-06-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Good_Health_Wellbeing', '0006_diet_alter_recipe_diet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='Good_Health_Wellbeing.ingredient'),
        ),
    ]
