# Generated by Django 6.0.5 on 2026-06-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Good_Health_Wellbeing', '0008_tags_remove_recipe_diet_alter_recipe_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Good_Health_Wellbeing.user'),
        ),
    ]
